//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dama.Organizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Attribute {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Attribute() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dama.Organizer.Resources.Attribute", typeof(Attribute).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values cannot be empty!.
        /// </summary>
        public static string Deadline_EmptyDeadline {
            get {
                return ResourceManager.GetString("Deadline_EmptyDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate or EndDate is incorrect!.
        /// </summary>
        public static string Deadline_IncorrectDeadline {
            get {
                return ResourceManager.GetString("Deadline_IncorrectDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid StartTime or EndTime value!.
        /// </summary>
        public static string Deadline_InvalidDeadline {
            get {
                return ResourceManager.GetString("Deadline_InvalidDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time field cannot be empty!.
        /// </summary>
        public static string Duration_EmptyDuration {
            get {
                return ResourceManager.GetString("Duration_EmptyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time field is incorrect, correct format is: &apos;hh:mm:ss&apos;.
        /// </summary>
        public static string Duration_IncorrectFormat {
            get {
                return ResourceManager.GetString("Duration_IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a given interval is allowed: [{0}m - {1}h]!.
        /// </summary>
        public static string Duration_IncorrectRange {
            get {
                return ResourceManager.GetString("Duration_IncorrectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End field cannot be empty!.
        /// </summary>
        public static string End_EmptyEnd {
            get {
                return ResourceManager.GetString("End_EmptyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End field has an incorrect value!.
        /// </summary>
        public static string End_IncorrectEndValue {
            get {
                return ResourceManager.GetString("End_IncorrectEndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start or end value!.
        /// </summary>
        public static string End_InvalidEndValue {
            get {
                return ResourceManager.GetString("End_InvalidEndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxTime field cannot be empty!.
        /// </summary>
        public static string MaxTime_EmptyMaxTime {
            get {
                return ResourceManager.GetString("MaxTime_EmptyMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxTime field has an incorrect value!.
        /// </summary>
        public static string MaxTime_IncorrectMaxTime {
            get {
                return ResourceManager.GetString("MaxTime_IncorrectMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference must be at least {0} minutes!.
        /// </summary>
        public static string MaxTime_IncorrectMaxTimeDifference {
            get {
                return ResourceManager.GetString("MaxTime_IncorrectMaxTimeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxTime value must be in {0} - {1} range!.
        /// </summary>
        public static string MaxTime_IncorrectMaxTimeRange {
            get {
                return ResourceManager.GetString("MaxTime_IncorrectMaxTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t leave any date fields empty!.
        /// </summary>
        public static string Milestone_EmptyMilestone {
            get {
                return ResourceManager.GetString("Milestone_EmptyMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of each name fields must be between {0} and {1} characters!.
        /// </summary>
        public static string Milestone_IncorrectMilestoneName {
            get {
                return ResourceManager.GetString("Milestone_IncorrectMilestoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each milestone values must be in {0} - {1} range!.
        /// </summary>
        public static string Milestone_IncorrectRange {
            get {
                return ResourceManager.GetString("Milestone_IncorrectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinTime field cannot be empty!.
        /// </summary>
        public static string MinTime_EmptyMinTime {
            get {
                return ResourceManager.GetString("MinTime_EmptyMinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinTime field has an incorrect value!.
        /// </summary>
        public static string MinTime_IncorrectMinTime {
            get {
                return ResourceManager.GetString("MinTime_IncorrectMinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinTime value must be in {0} - {1} range!.
        /// </summary>
        public static string MinTime_IncorrectMinTimeRange {
            get {
                return ResourceManager.GetString("MinTime_IncorrectMinTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority field cannot be empty!.
        /// </summary>
        public static string Priority_EmptyPriority {
            get {
                return ResourceManager.GetString("Priority_EmptyPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority field has an incorrect value!.
        /// </summary>
        public static string Priority_IncorrectPriority {
            get {
                return ResourceManager.GetString("Priority_IncorrectPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority value must be in {0} - {1} range!.
        /// </summary>
        public static string Priority_IncorrectPriorityRanged {
            get {
                return ResourceManager.GetString("Priority_IncorrectPriorityRanged", resourceCulture);
            }
        }
    }
}
