using Dama.Data.Models;
using Dama.Data.Sql.Repositories;
using Dama.Data.Sql.SQL;
using Dama.Web.Controllers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;

namespace Dama.Data.UnitTest
{
    [TestClass]
    public class IRepositoryTest
    {
        FixedActivity fixedActivity1;
        FixedActivity fixedActivity2;
        FixedActivity fixedActivity3;

        List<FixedActivity> fixedActivities;
        GenericIRepository<FixedActivity> fixedActivityRepository;
        UnitOfWork unitOfWork;
        CalendarController calendarController;

        public IRepositoryTest()
        {
            CreateFixedActivities();
            fixedActivities = new List<FixedActivity>() { fixedActivity1, fixedActivity2, fixedActivity3 };
            fixedActivityRepository = new GenericIRepository<FixedActivity>(fixedActivities);
            unitOfWork = new UnitOfWork(fixedActivityRepository: fixedActivityRepository);
            calendarController = new CalendarController(unitOfWork, new RepositorySettings());
        }

        private void CreateFixedActivities()
        {
            fixedActivity1 = new FixedActivity("FA1",
                                 "Fixed activity 1",
                                 Enums.Color.Black,
                                 Enums.CreationType.AutoGenerated,
                                 new List<Label>() { new Label("Label1", "1"), new Label("Label2", "1") },
                                 new Category("CAT1", "Category 1", Enums.Color.Blue, 10, "1"), "1", 10,
                                 new DateTime(2020, 03, 29, 10, 0, 0), new DateTime(2020, 03, 29, 11, 0, 0), false);

            fixedActivity2 = new FixedActivity("FA2",
                                  "Fixed activity 2",
                                  Enums.Color.Red,
                                  Enums.CreationType.ManuallyCreated,
                                  new List<Label>() { new Label("Label1", "2"), new Label("Label2", "2") },
                                  new Category("CAT1", "Category 1", Enums.Color.Green, 10, "2"), "2", 10,
                                  new DateTime(2020, 03, 29, 13, 0, 0), new DateTime(2020, 03, 29, 19, 0, 0), false);

            fixedActivity3 = new FixedActivity("FA3",
                                  "Fixed activity 3",
                                  Enums.Color.Gray,
                                  Enums.CreationType.ManuallyCreated,
                                  new List<Label>() { new Label("Label1", "3"), new Label("Label2", "3") },
                                  new Category("CAT1", "Category 1", Enums.Color.Yellow, 10, "3"), "3", 10,
                                  new DateTime(2020, 03, 29, 10, 30, 0), new DateTime(2020, 03, 29, 18, 10, 0), false);
        }
    }
}
